In [2]:
import numpy as np

#Creating vector

In [3]:
row_vect = np.array([1,2,3])
col_vect = np.array([[1],[2],[3]])

In [4]:
print(row_vect)

[1 2 3]


In [5]:
col_vect

array([[1],
       [2],
       [3]])

In [6]:
rvec = np.arange(0,9)
rvec

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
from scipy import sparse

In [8]:
matrix = np.array([[0,0,0],[1,0,1],[3,2,0]])

In [9]:
matrix

array([[0, 0, 0],
       [1, 0, 1],
       [3, 2, 0]])

In [10]:
sparseM=sparse.csr_matrix(matrix)
#CSR Compressed Sparse Row matrix

In [11]:
print(sparseM)

  (1, 0)	1
  (1, 2)	1
  (2, 0)	3
  (2, 1)	2


In [12]:
print(matrix[2:]) #last row of matrix

[[3 2 0]]


In [13]:
#coo_matrix A sparse matrix in COOrdinate format.
#csc_matrix Compressed Sparse Column matrix

In [14]:
print(matrix[0:2]) #first two rows

[[0 0 0]
 [1 0 1]]


In [15]:
matrix[0][1] 

0

In [16]:
matrix[1][2]

1

In [17]:
print(matrix[:,2])

[0 1 0]


In [18]:
#[00,01,02
# 10,11,12
# 20,21,22]


In [19]:
matrix2 = np.array([[1,2,0],[1,6,1],[9,2,0]])

In [20]:
add= matrix + matrix2
print(add)

[[ 1  2  0]
 [ 2  6  2]
 [12  4  0]]


In [21]:
sub = matrix - matrix2
print(sub)

[[-1 -2  0]
 [ 0 -6  0]
 [-6  0  0]]


In [22]:
mul = matrix * matrix2
print(mul)

[[ 0  0  0]
 [ 1  0  1]
 [27  4  0]]


In [23]:
div = matrix / matrix2
print(div)

[[0.         0.                nan]
 [1.         0.         1.        ]
 [0.33333333 1.                nan]]


D:\ana\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [24]:
matrix + matrix2

array([[ 1,  2,  0],
       [ 2,  6,  2],
       [12,  4,  0]])

In [25]:
var = np.var(matrix)
var

1.0617283950617287

In [26]:
std = np.std(matrix)
std #standard deviation of matrix

1.0304020550550783

In [27]:
std1 =np.std(mul)
std1 #std of mul matrix

8.339997335464535

In [28]:
trans = np.transpose(matrix)
trans

array([[0, 1, 3],
       [0, 0, 2],
       [0, 1, 0]])

In [29]:
rank=np.linalg.matrix_rank(matrix)
rank

2

In [31]:
deter = np.linalg.det(add)
deter #determinant of add matrix

40.000000000000036

In [34]:
inv = np.linalg.inv(add)
print(inv) #inverse add matrix

[[-0.2   0.    0.1 ]
 [ 0.6   0.   -0.05]
 [-1.6   0.5   0.05]]


In [37]:
ranmat = np.random.randint(2, 10, 4)
ranmat #random array

array([3, 9, 7, 7])

In [40]:
ranmat1 = np.random.randint(2, 10, (3,3))
ranmat1 #random matrix of 3x3

array([[3, 3, 6],
       [3, 8, 3],
       [4, 2, 2]])